### ISSUE TITLE
Electrical Connection FYI

### ISSUE THREAD

**Issue by matthewmax09** [bitcraze/Bitcraze_PMW3901#1]
Hello, 

This isn't an issue but a documentation for the electrical connection. 

In addition to connecting CS, SCK, MISO, MOSI, Vcc, and Gnd, there is an additional pin to connect which would be the VCOM pin to VCC as the TLV702 takes in a voltage between 2.0 to 5.5V and outputs 1.8V to the PMW3901. I had assumed that the voltage regulator would have automatically taken its input from Vcc, much to my surprise at the end of the working day. 

So the connections from PMW3901 to Teensy 3.5 board looks like this:

| Bitcraze Flow Deck | Teensy 3.5/Arduino Board |
|--------------------|--------------------------|
| Vcc                | Vcc                      |
| Gnd                | Gnd                      |
| CS                 | CS0                      |
| SCK                | SCK0                     |
| MISO               | MISO0                    |
| MOSI               | MOSI0                    |
| VCOM               | Vcc                      | 

Hope this helps some of you in your sensor setup!

**Comment by ataffanel** [comment]
Hi, yes this is a Crazyflie design: VCOM is the battery voltage, if a deck has its own regulator we will power it with  VCOM in order to avoid loading the Crazyflie 3V regulator needlessly.

Thanks for the doc, I keep this ticket open to give it some visibility until the Flow breakout is out.

**Comment by ataffanel** [comment]
The flow breakout is now released so I am closing this ticket.
