### ISSUE TITLE
Framebuffer grab is extremely slow - depending on register magic

### ISSUE THREAD

**Issue by 222464** [bitcraze/Bitcraze_PMW3901#11]
Hello,

I am trying to use this  sensor as a tiny camera for a very small machine vision project. With the code as-is, the framebuffer grab gets the images but at a very slow framerate - about 7 seconds per frame or so. It seems the status waiting is the slowest part in the framebuffer get code.

I would be interested to know how the register settings to enable the framebuffer grab were found in the first place - I cannot find any documentation.

I tried commenting out random registers, and tried some different settings I found in other PMW3901 libraries. I found 2 combinations that affect the result - I was able to get a framerate of about 2 seconds per frame with one combination. Another combination yielded 1 second per frame, but the image became very dark, making it useless.

Does anyone have any ideas on how to get a decent frame rate? I would be fine with 1 second per frame if the image were not so dark.

**Comment by dstulken** [comment]
> I tried commenting out random registers, and tried some different settings I found in other PMW3901 libraries. I found 2 combinations that affect the result - I was able to get a framerate of about 2 seconds per frame with one combination. Another combination yielded 1 second per frame, but the image became very dark, making it useless.

Would you mind sharing those changes that you've tried?

**Comment by 222464** [comment]
Sorry, unfortunately I lost the code for it - my computer was wiped a while back, so I don't know anymore :(
