### ISSUE TITLE
Poor mouse emulation

### ISSUE THREAD

**Issue by Tonymazzz** [bitcraze/Bitcraze_PMW3901#14]
Hello!!

I have mounted the sensor on a kind of mouse and I use it as a laser, everything works but when jumping from surfaces to different ones it behaves as if it vibrates or stops for moments until you reload a surface that the sensor like, let's say it's hard to draw a circle in Paint without shaking or losing track a bit.

I am using it from 1 meter to arround 2-5 meters. Any advice please?

Thank you very much in advance!!

**Comment by knmcguire** [comment]
Hi!

We need more information about your problem. What kind of surface are you using it over and what color or texture? It needs to be able to go over something that is well lit and has good textures.

**Comment by knmcguire** [comment]
closed due to inactivity
