### ISSUE TITLE
Bugs compensate themselves

### ISSUE THREAD

**Issue by ScalyDragon** [bitcraze/Bitcraze_PMW3901#16]
In Line 54 of Bitcraze_PMW3901.cpp there is a test for the inverse chip-id. As the inverse Chip-ID is 0xB6 and not 0xB8 the comparison dIpihc != 0xB8 is always true, so you only check for the chipId effectively. As the code seems to be copied from the Crazyflie-Code the logical AND should be changed to an OR to check correctly, and then the comparison with the broken inverse ID fails as expected.

**Comment by krichardsson** [comment]
Thanks for notifying us
