### ISSUE TITLE
Flow deck and flow breakout board difference

### ISSUE THREAD

**Issue by RobertoIV** [bitcraze/Bitcraze_PMW3901#3]
I have a flow deck and I was wondering if both boards work the same way or do I necessary need too buy a new flow breakout board to be able to use this example with arduino?

**Comment by ataffanel** [comment]
Both boards contains the same main IC but are different in terms of power management and IO signal levels. The deck is designed to be connected to the 3.0V Crazyflie while the breakout can connect to a 5V Arduino. You will be able to use the deck with a 3.3V arduino, just make sure you cable things well by checking the board schematic: https://wiki.bitcraze.io/_media/projects:crazyflie2:expansionboards:flow-deck_reve.pdf and https://wiki.bitcraze.io/_media/breakout:flow_breakout_revb.pdf
