### ISSUE TITLE
Origins of the "performance optimization" initialization 

### ISSUE THREAD

**Issue by braincore** [bitcraze/Bitcraze_PMW3901#4]
I'm writing a PMW3901 library for Rust and was examining this library when I stumbled on the initialization sequencing opaquely writing to 70+ registers (`Bitcraze_PMW3901::initRegisters()`). Where did this sequence come from and what does it do?

Thanks for the helpful library!

**Comment by ataffanel** [comment]
Hi, unfortunately this is proprietary magic numbers and we do not know what it is doing in details. It is initializing the sensor and has been tuned for being used on the Crazyflie 2.0 as far as I know, it should be good for general purpose use of the sensor. If you happen to have specific tuning needs of the sensor you would need to contact the sensor manufacturer.

Porting the driver to rust sounds interesting, is it intended to run on an bare-metal embedded system?

**Comment by braincore** [comment]
Yes, that's correct: Raspberry Pi, Beaglebone, NVIDIA Jetson, etc... The library is [here](https://github.com/braincore/pmw3901-rs).
