### ISSUE TITLE
Working on adding a pixel grabbing framebuffer

### ISSUE THREAD

**Issue by ArsenioDev** [bitcraze/Bitcraze_PMW3901#5]
What really intrigued me about this sensor is the ability to grab the 35*35 pixel array as a frame, I've gotten >60fps out of the debug frame extraction on the ADNS3080 but that is absolutely massive in comparison to this.

**Comment by ataffanel** [comment]
Sounds interesting, do you already have a prototype of image grabing working?

**Comment by 4perros** [comment]
I hope you get the prototype working!! 
Regards
Rodrigo
Happy holidays

**Comment by ArsenioDev** [comment]
So far I have it intitializing and dumping frame, but in the wrong format and that's not compatible with my arbitrary frame array plugin vision system. Still needs more work

**Comment by 4perros** [comment]
Hi
Is it possible to see what you have done so far? 
Regards
Rodrigo

**Comment by ArsenioDev** [comment]
![image](https://user-images.githubusercontent.com/13143666/67625108-903eb900-f807-11e9-82f0-ba812a2c7737.png)

Here's where I am at the moment, have the framebuffer dumping but it's freezing after one frame that takes several seconds to acquire.

**Comment by ArsenioDev** [comment]
#9  Validated looping code, full functionality available.
