### ISSUE TITLE
improvement request

### ISSUE THREAD

**Issue by naughtyStark** [bitcraze/Bitcraze_PMW3901#6]
Hi,
    I was going through the .cpp file and I noticed that for taking one X,Y motion reading, it reads 5 registers and in each register read there is a net delay of 400us, meaning that it takes ~2ms for a complete update. While an RTOS like chibiOS could solve that problem, I really wish the delays weren't required (at least not 400 us delays per register read). Could you look into this? Also the reason why I don't wanna use ChibiOS is because I have no extra space for an RTOS. I'm working on a blue pill and the memory capacity is only 128K.

Thanks,
Regards,
Sidharth T.

**Comment by linarism** [comment]
Hey Sidharth,

Check out [my take](https://github.com/Vectorotor/Bitcraze_PMW3901) on a single read for all needed data. Note my code is for the Teensy 3.6.

**Comment by naughtyStark** [comment]
Wow. This is exactly the kind of thing I wanted! Thank you so much. Can you please put your copyright or something in your files so that I can copy it without plagiarism? 

Thanks,
Regards,
Sidharth T.

**Comment by naughtyStark** [comment]
Also maybe you should create a pull request for your fork so that this main one can be improved.

**Comment by linarism** [comment]
Hey Sidharth,

I maintained the MIT license so you're free to use my fork as you will. I'm reluctant to create a pull request because I made major architectural changes on my fork and am not sure if it fits within the same functional intent.

**Comment by naughtyStark** [comment]
Excellent. I will still however give you a shout out. Your work has been of extreme help to me. Thank you. I too was looking for a datasheet for the sensor and it appears it has been deleted by the pixart people
