### ISSUE TITLE
Datasheet copy

### ISSUE THREAD

**Issue by linarism** [bitcraze/Bitcraze_PMW3901#7]
Hello,

I've been using the PMW3901 with good success thus far, but any changes I make are either through experimentation or using other PixArt sensor datasheets, as I'm unable to find a useful integrator guide for this particular sensor. Would anyone have a copy to add to the repository or a download link?

Thanks,

Linar

**Comment by ataffanel** [comment]
There is a public version of the PMW3901 datasheet on Bitcraze's wiki: https://wiki.bitcraze.io/projects:crazyflie2:expansionboards:flow-v2. If you need more information about the chip you need to contact PixArt directly.
