### ISSUE TITLE
Matching "tick" to real measure

### ISSUE THREAD

**Issue by Titibo26** [bitcraze/Bitcraze_PMW3901#8]
Hi,

I'd like to know what is the scalar value in the formula of the distance moved ? how can we know this value ? 
Also, the sensor resolution is 30x30 Px right ? 
I'd like to compare theorical value with my testing value. (im using it on a wheeled robot).
Thanks,

TD

**Comment by ataffanel** [comment]
You can find an example implementation in the Crazyflie firmware: https://github.com/bitcraze/crazyflie-firmware/blob/master/src/modules/src/kalman_core.c#L420. Most if not all constant where found by experiments.
